#!/bin/bash
list='
Example_cancellation.1c.c
Example_declare_target.2c.c
Example_init_lock.1c.c
Example_init_lock_with_hint.1c.c
Example_pra_iterator.1c.c
Example_target_data.5c.c
Example_threadprivate.3c.c
Example_threadprivate.4c.c
Example_threadprivate.5c.c
'
for i in $list; do
   echo " Working on $i"
done
